name: Build and Deploy
run-name: build-and-deploy

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build
        run: |
          make build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/public
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
